[project]
name = "trip-planner"
version = "0.1.0"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = []

[tool.mypy]
exclude = ["1\\. tests"]
